homepage:
  url:    /
  param:  { module: default, action: index, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

##-------------------------- shfSecurity --------------------------##
shfSecurity_index:
  url:    /signin
  param:  { module: shfSecurity, action: index, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

shfSecurity_login:
  url:    /login
  param:  { module: shfSecurity, action: login, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php
    - model/base/usuarioCredencialBaseTableClass.php
    - model/usuarioCredencialTableClass.php
    - model/base/credencialBaseTableClass.php
    - model/credencialTableClass.php
    - model/base/recordarMeBaseTableClass.php
    - model/recordarMeTableClass.php
    - hooks/logHookClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php

shfSecurity_logout:
  url:    /logout
  param:  { module: shfSecurity, action: logout, format: html }
  load:
    - model/base/recordarMeBaseTableClass.php
    - model/recordarMeTableClass.php
    - hooks/logHookClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
##-------------------------- shfSecurity --------------------------##

##-------------------------- EJEMPLO --------------------------##
default_index:
  url:    /usuarios/index
  param:  { module: default, action: index, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

default_insert:
  url:    /usuarios/insertar
  param:  { module: default, action: insert, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php
    
default_view:
  url:    /usuarios/ver
  param:  { module: default, action: view, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

default_create:
  url:    /usuarios/crear
  param:  { module: default, action: create, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

default_edit:
  url:    /usuario/editar
  param:  { module: default, action: edit, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

default_update:
  url:    /usuario/actualizar
  param:  { module: default, action: update, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

default_delete:
  url:    /usuario/eliminar
  param:  { module: default, action: delete, format: json }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

default_deleteSelect:
  url:    /usuario/eliminarSeleccion
  param:  { module: default, action: deleteSelect, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

default_reporte:
  url:    /usuario/reporte
  param:  { module: default, action: report, format: pdf }
##-------------------------- EJEMPLO --------------------------##

##-------------------------- TIPO EMPAQUE --------------------------##

tipoEmpaque_index:
  url:    /tipoEmpaque/index
  param:  { module: tipoEmpaque, action: index, format: html }
  load:
    - model/base/tipoEmpaqueBaseTableClass.php
    - model/tipoEmpaqueTableClass.php

tipoEmpaque_insert:
  url:    /tipoEmpaque/insertar
  param:  { module: tipoEmpaque, action: insert, format: html }
  load:
    - model/base/tipoEmpaqueBaseTableClass.php
    - model/tipoEmpaqueTableClass.php
    
tipoEmpaque_view:
  url:    /tipoEmpaque/ver
  param:  { module: tipoEmpaque, action: view, format: html }
  load:
    - model/base/tipoEmpaqueBaseTableClass.php
    - model/tipoEmpaqueTableClass.php

tipoEmpaque_create:
  url:    /tipoEmpaque/crear
  param:  { module: tipoEmpaque, action: create, format: html }
  load:
    - model/base/tipoEmpaqueBaseTableClass.php
    - model/tipoEmpaqueTableClass.php

tipoEmpaque_edit:
  url:    /tipoEmpaque/editar
  param:  { module: tipoEmpaque, action: edit, format: html }
  load:
    - model/base/tipoEmpaqueBaseTableClass.php
    - model/tipoEmpaqueTableClass.php

tipoEmpaque_update:
  url:    /tipoEmpaque/actualizar
  param:  { module: tipoEmpaque, action: update, format: html }
  load:
    - model/base/tipoEmpaqueBaseTableClass.php
    - model/tipoEmpaqueTableClass.php

tipoEmpaque_delete:
  url:    /tipoEmpaque/eliminar
  param:  { module: tipoEmpaque, action: delete, format: json }
  load:
    - model/base/tipoEmpaqueBaseTableClass.php
    - model/tipoEmpaqueTableClass.php

tipoEmpaque_deleteSelect:
  url:    /tipoEmpaque/eliminarSeleccion
  param:  { module: tipoEmpaque, action: deleteSelect, format: html }
  load:
    - model/base/tipoEmpaqueBaseTableClass.php
    - model/tipoEmpaqueTableClass.php

##-------------------------- TIPO EMPAQUE --------------------------##
##-------------------------- TIPO ID --------------------------##

tipoId_index:
  url:    /tipoId/index
  param:  { module: tipoId, action: index, format: html }
  load:
    - model/base/tipoIdBaseTableClass.php
    - model/tipoIdTableClass.php

tipoId_insert:
  url:    /tipoId/insertar
  param:  { module: tipoId, action: insert, format: html }
  load:
    - model/base/tipoIdBaseTableClass.php
    - model/tipoIdTableClass.php
    
tipoId_view:
  url:    /tipoId/ver
  param:  { module: tipoId, action: view, format: html }
  load:
    - model/base/tipoIdBaseTableClass.php
    - model/tipoIdTableClass.php

tipoId_create:
  url:    /tipoId/crear
  param:  { module: tipoId, action: create, format: html }
  load:
    - model/base/tipoIdBaseTableClass.php
    - model/tipoIdTableClass.php

tipoId_edit:
  url:    /tipoId/editar
  param:  { module: tipoId, action: edit, format: html }
  load:
    - model/base/tipoIdBaseTableClass.php
    - model/tipoIdTableClass.php

tipoId_update:
  url:    /tipoId/actualizar
  param:  { module: tipoId, action: update, format: html }
  load:
    - model/base/tipoIdBaseTableClass.php
    - model/tipoIdTableClass.php

tipoId_delete:
  url:    /tipoId/eliminar
  param:  { module: tipoId, action: delete, format: json }
  load:
    - model/base/tipoIdBaseTableClass.php
    - model/tipoIdTableClass.php

tipoId_deleteSelect:
  url:    /tipoId/eliminarSeleccion
  param:  { module: tipoId, action: deleteSelect, format: html }
  load:
    - model/base/tipoIdBaseTableClass.php
    - model/tipoIdTableClass.php

##-------------------------- TIPO EMPAQUE --------------------------##
##-------------------------- CIUDAD---------------------------------##

ciudad_index:
  url:    /ciudad/index
  param:  { module: ciudad, action: index, format: html }
  load:
    - model/base/ciudadBaseTableClass.php
    - model/ciudadTableClass.php

ciudad_insert:
  url:    /ciudad/insertar
  param:  { module: ciudad, action: insert, format: html }
  load:
    - model/base/ciudadBaseTableClass.php
    - model/ciudadTableClass.php
    
ciudad_view:
  url:    /ciudad/ver
  param:  { module: ciudad, action: view, format: html }
  load:
    - model/base/ciudadBaseTableClass.php
    - model/ciudadTableClass.php

ciudad_create:
  url:    /ciudad/crear
  param:  { module: ciudad, action: create, format: html }
  load:
    - model/base/ciudadBaseTableClass.php
    - model/ciudadTableClass.php

ciudad_edit:
  url:    /ciudad/editar
  param:  { module: ciudad, action: edit, format: html }
  load:
    - model/base/ciudadBaseTableClass.php
    - model/ciudadTableClass.php

ciudad_update:
  url:    /ciudad/actualizar
  param:  { module: ciudad, action: update, format: html }
  load:
    - model/base/ciudadBaseTableClass.php
    - model/ciudadTableClass.php

ciudad_delete:
  url:    /ciudad/eliminar
  param:  { module: ciudad, action: delete, format: json }
  load:
    - model/base/ciudadBaseTableClass.php
    - model/ciudadTableClass.php

ciudad_deleteSelect:
  url:    /ciudad/eliminarSeleccion
  param:  { module: ciudad, action: deleteSelect, format: html }
  load:
    - model/base/ciudadBaseTableClass.php
    - model/ciudadTableClass.php

##-------------------------- CIUDAD--------------------------------##

##-------------------------- TIPO PAGO-----------------------------##

tipoPago_index:
  url:    /tipoPago/index
  param:  { module: tipoPago, action: index, format: html }
  load:
    - model/base/tipoPagoBaseTableClass.php
    - model/tipoPagoTableClass.php

tipoPago_insert:
  url:    /tipoPago/insertar
  param:  { module: tipoPago, action: insert, format: html }
  load:
    - model/base/tipoPagoBaseTableClass.php
    - model/tipoPagoTableClass.php
    
tipoPago_view:
  url:    /tipoPago/ver
  param:  { module: tipoPago, action: view, format: html }
  load:
    - model/base/tipoPagoBaseTableClass.php
    - model/tipoPagoTableClass.php

tipoPago_create:
  url:    /tipoPago/crear
  param:  { module: tipoPago, action: create, format: html }
  load:
    - model/base/tipoPagoBaseTableClass.php
    - model/tipoPagoTableClass.php

tipoPago_edit:
  url:    /tipoPago/editar
  param:  { module: tipoPago, action: edit, format: html }
  load:
    - model/base/tipoPagoBaseTableClass.php
    - model/tipoPagoTableClass.php

tipoPago_update:
  url:    /tipoPago/actualizar
  param:  { module: tipoPago, action: update, format: html }
  load:
    - model/base/tipoPagoBaseTableClass.php
    - model/tipoPagoTableClass.php

tipoPago_delete:
  url:    /tipoPago/eliminar
  param:  { module: tipoPago, action: delete, format: json }
  load:
    - model/base/tipoPagoBaseTableClass.php
    - model/tipoPagoTableClass.php

tipoPago_deleteSelect:
  url:    /tipoPago/eliminarSeleccion
  param:  { module: tipoPago, action: deleteSelect, format: html }
  load:
    - model/base/tipoPagoBaseTableClass.php
    - model/tipoPagoTableClass.php

##-------------------------- TIPO PAGO----------------------------##