homepage:
  url:    /
  param:  { module: default, action: index, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

##-------------------------- shfSecurity --------------------------##
shfSecurity_index:
  url:    /signin
  param:  { module: shfSecurity, action: index, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

shfSecurity_login:
  url:    /login
  param:  { module: shfSecurity, action: login, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php
    - model/base/usuarioCredencialBaseTableClass.php
    - model/usuarioCredencialTableClass.php
    - model/base/credencialBaseTableClass.php
    - model/credencialTableClass.php
    - model/base/recordarMeBaseTableClass.php
    - model/recordarMeTableClass.php
    - hooks/logHookClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php

shfSecurity_logout:
  url:    /logout
  param:  { module: shfSecurity, action: logout, format: html }
  load:
    - model/base/recordarMeBaseTableClass.php
    - model/recordarMeTableClass.php
    - hooks/logHookClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
##-------------------------- shfSecurity --------------------------##

##-------------------------- EJEMPLO --------------------------##
default_index:
  url:    /usuarios/index
  param:  { module: default, action: index, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

default_insert:
  url:    /usuarios/insertar
  param:  { module: default, action: insert, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php
    
default_view:
  url:    /usuarios/ver
  param:  { module: default, action: view, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

default_create:
  url:    /usuarios/crear
  param:  { module: default, action: create, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

default_edit:
  url:    /usuario/editar
  param:  { module: default, action: edit, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

default_update:
  url:    /usuario/actualizar
  param:  { module: default, action: update, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

default_delete:
  url:    /usuario/eliminar
  param:  { module: default, action: delete, format: json }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

default_deleteSelect:
  url:    /usuario/eliminarSeleccion
  param:  { module: default, action: deleteSelect, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

default_reporte:
  url:    /usuario/reporte
  param:  { module: default, action: report, format: pdf }
##-------------------------- EJEMPLO --------------------------##

##-------------------------- TIPO EMPAQUE --------------------------##

tipoEmpaque_index:
  url:    /tipoEmpaque/index
  param:  { module: tipoEmpaque, action: index, format: html }
  load:
    - model/base/tipoEmpaqueBaseTableClass.php
    - model/tipoEmpaqueTableClass.php

tipoEmpaque_insert:
  url:    /tipoEmpaque/insertar
  param:  { module: tipoEmpaque, action: insert, format: html }
  load:
    - model/base/tipoEmpaqueBaseTableClass.php
    - model/tipoEmpaqueTableClass.php
    
tipoEmpaque_view:
  url:    /tipoEmpaque/ver
  param:  { module: tipoEmpaque, action: view, format: html }
  load:
    - model/base/tipoEmpaqueBaseTableClass.php
    - model/tipoEmpaqueTableClass.php

tipoEmpaque_create:
  url:    /tipoEmpaque/crear
  param:  { module: tipoEmpaque, action: create, format: html }
  load:
    - model/base/tipoEmpaqueBaseTableClass.php
    - model/tipoEmpaqueTableClass.php

tipoEmpaque_edit:
  url:    /tipoEmpaque/editar
  param:  { module: tipoEmpaque, action: edit, format: html }
  load:
    - model/base/tipoEmpaqueBaseTableClass.php
    - model/tipoEmpaqueTableClass.php

tipoEmpaque_update:
  url:    /tipoEmpaque/actualizar
  param:  { module: tipoEmpaque, action: update, format: html }
  load:
    - model/base/tipoEmpaqueBaseTableClass.php
    - model/tipoEmpaqueTableClass.php

tipoEmpaque_delete:
  url:    /tipoEmpaque/eliminar
  param:  { module: tipoEmpaque, action: delete, format: json }
  load:
    - model/base/tipoEmpaqueBaseTableClass.php
    - model/tipoEmpaqueTableClass.php

tipoEmpaque_deleteSelect:
  url:    /tipoEmpaque/eliminarSeleccion
  param:  { module: tipoEmpaque, action: deleteSelect, format: html }
  load:
    - model/base/tipoEmpaqueBaseTableClass.php
    - model/tipoEmpaqueTableClass.php

##-------------------------- TIPO EMPAQUE --------------------------##