shfSecurity:
  index:
    security: false
  login:
    security: false
  logout:
    security: true
  noPermission:
    security: false
  exception:
    security: false

default:
  index:
    security: true
    credentials:
      - [admin, Carlos]
  insert:
    security: true
  
control_calidad:
  index:
    security: true
    credentials:
      - [admin, Carlos]
  insert:
    security: true
