shfSecurity:
  index:
    security: false
  login:
    security: false
  logout:
    security: true
  noPermission:
    security: false
  exception:
    security: false

usuario:
  index:
    security: true
    credentials:
      - [admin, Consultor]
  insert:
    security: true
    
controlCalidad:
  index:
    security: true
    credentials:
      - [admin, Consultor]
  insert:
    security: true
  create:
    security: true


entradaBodega:
  index:
    security: true
    credentials:
      - [admin, Consultor]
  insert:
    security: true
  create:
    security: true
    
salidaBodega:
  index:
    security: true
    credentials:
      - [admin, Consultor]
  insert:
    security: true
  create:
    security: true        
        
detalleEntrada:
  index:
    security: true
    credentials:
      - [admin, Consultor]
  insert:
    security: true
  create:
    security: true
    
insumo:
  index:
    security: true
    credentials:
      - [admin, Consultor]
  insert:
    security: true
  create:
    security: true
    
tipoInsumo:
  index:
    security: true
    credentials:
      - [admin, Consultor]
  insert:
    security: true
  create:
    security: true
     
empleado:
  index:
    security: true
    credentials:
        - [admin, Consultor]
  insert:
    security: true
    credentials:
      - [admin]
  create:
    security: true
    credentials:
      - [admin]
  delete:
    security: true
    credentials:
      - [admin]
    
credencial:
  index:
    security: true
    credentials:
      - [admin, Consultor]
  insert:
    security: true
  create:
    security: true
  delete:
    security: true
    
tipoId:
  index:
    security: true
    credentials:
      - [admin, Consultor]
  insert:
    security: true
  create:
    security: true
  delete:
    security: true
    
empaque:
  index:
    security: true
    credentials:
      - [admin, Consultor]
  insert:
    security: true
  create:
    security: true
  delete:
    security: true

pagoTrabajadores:
  index:
    security: true
    credencial:
      -[admin, Consultor]
  insert:
    security: true
  create:
    security: true
  delete:
    security: true