shfSecurity:
  index:
    security: false
  login:
    security: false
  logout:
    security: true
  noPermission:
    security: false
  exception:
    security: false

default:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
    
controlCalidad:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
  create:
    security: true