shfSecurity:
  index:
    security: false
  login:
    security: false
  logout:
    security: true
  noPermission:
    security: false
  exception:
    security: false

default:
  index:
    security: true
    credentials:
      - [admin, Carlos]
  insert:
    security: true
    
controlCalidad:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
  create:
    security: true


entradaBodega:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
  create:
    security: true
    
        
detalleEntrada:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
  create:
    security: true
     
empleado:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
  create:
    security: true
  delete:
    security: true
    
credencial:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
  create:
    security: true
  delete:
    security: true
    
tipoId:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
  create:
    security: true
  delete:
    security: true