all:
  favicon: hola.ico
  title: titulo de la p‡gina general
  meta:
    - charset="UTF-8"
  javascript:
    - jquery-1.11.1.min.js
    - bootstrap.js
  stylesheet:
    - bootstrap.css
    - main.css

shfSecurity:
  index:
    title: Identificaci—n de usuario
    stylesheet:
      - signin.css

default:
  index:
    javascript:
      - index.js
      
tipoEmpaque:
  index:
    title: Tipo Empaque
    javascript:
      - index.js
  edit:
    title: Editar Tipo Empaque
    
  view:
    title: Ver Tipo Empaque

credencial:
  index:
    title: Credencial
    javascript:
      - index.js
  edit:
    title: Editar Credencial
    
  view:
    title: Ver Credenciales

tipoId:
  index:
    title: Tipo Id
    javascript:
      - index.js
  edit:
    title: Editar Tipo Identificacion
    
  view:
    title: Ver Tipo Identificacion  
    
empleado:
  index:
    title: Empleado
    javascript:
      - index.js
  edit:
    title: Editar Empleado
    
  view:
    title: Ver Empleado
       
ciudad:
  index:
    title: Ciudad
    javascript:
      - index.js
  edit:
    title: Editar Ciudad
    
  view:
    title: Ver Ciudad
    
tipoPago:
  index:
    title: Tipo Pago
    javascript:
      - index.js
  edit:
    title: Editar Tipo Pago
    
  view:
    title: Ver Tipo Pago
    
pagoTrabajadores:
  index:
    title: Pago de Trabajadores
    javascript:
      - index.js
  edit:
    title: Editar Pago de Trabajadores
    
  view:
    title: Ver Pago de Trabajadores


entradaBodega:
  index:
    title: Entrada de Bodega
    javascript:
      - index.js
  edit:
    title: Editar Entrada de Bodega
    
  view:
    title: Ver Entrada de Bodega
    
tipoInsumo:
  index:
    title: Tipo Insumo
    javascript:
      - index.js
  edit:
    title: Editar Tipo Insumo
    
  view:
    title: Ver Tipo Insumo
    
proveedor:
  index:
    title: Proveedor
    javascript:
      - index.js
  edit:
    title: Editar Proveedor
    
  view:
    title: Ver Proveedor
    
tipoDoc:
  index:
    title: Tipo Documento
    javascript:
      - index.js
  edit:
    title: Editar Tipo Documento
    
  view:
    title: Ver Tipo Documento