--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

--
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


SET search_path = public, pg_catalog;

--
-- Name: bitacora_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE bitacora_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE bitacora_id_seq OWNER TO postgres;

--
-- Name: SEQUENCE bitacora_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE bitacora_id_seq IS 'DbWrench Autogenerated Sequence.';


SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: bitacora; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE bitacora (
    id bigint DEFAULT nextval('bitacora_id_seq'::regclass) NOT NULL,
    usuario_id bigint NOT NULL,
    accion character varying(80) NOT NULL,
    tabla character varying(80) NOT NULL,
    registro bigint,
    observacion character varying(1024),
    fecha timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE bitacora OWNER TO postgres;

--
-- Name: bitacora_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "bitacora_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "bitacora_Id_seq" OWNER TO postgres;

--
-- Name: SEQUENCE "bitacora_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "bitacora_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- Name: ciudad_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "ciudad_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "ciudad_Id_seq" OWNER TO postgres;

--
-- Name: SEQUENCE "ciudad_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "ciudad_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- Name: ciudad; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE ciudad (
    id integer DEFAULT nextval('"ciudad_Id_seq"'::regclass) NOT NULL,
    nom_ciudad character varying(40)
);


ALTER TABLE ciudad OWNER TO postgres;

--
-- Name: control_calidad_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "control_calidad_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "control_calidad_Id_seq" OWNER TO postgres;

--
-- Name: SEQUENCE "control_calidad_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "control_calidad_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- Name: control_calidad; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE control_calidad (
    id integer DEFAULT nextval('"control_calidad_Id_seq"'::regclass) NOT NULL,
    empleado_id integer,
    proveedor_id integer,
    turno character varying(10),
    brix bigint,
    ph bigint,
    ar bigint,
    sacarosa bigint,
    pureza bigint,
    fecha timestamp without time zone
);


ALTER TABLE control_calidad OWNER TO postgres;

--
-- Name: credencial_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE credencial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE credencial_id_seq OWNER TO postgres;

--
-- Name: SEQUENCE credencial_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE credencial_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- Name: credencial; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE credencial (
    id bigint DEFAULT nextval('credencial_id_seq'::regclass) NOT NULL,
    nombre character varying(80) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone
);


ALTER TABLE credencial OWNER TO postgres;

--
-- Name: credencial_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "credencial_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "credencial_Id_seq" OWNER TO postgres;

--
-- Name: SEQUENCE "credencial_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "credencial_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- Name: dato_usuario_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "dato_usuario_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "dato_usuario_Id_seq" OWNER TO postgres;

--
-- Name: SEQUENCE "dato_usuario_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "dato_usuario_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- Name: detalle_empaque_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "detalle_empaque_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "detalle_empaque_Id_seq" OWNER TO postgres;

--
-- Name: SEQUENCE "detalle_empaque_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "detalle_empaque_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- Name: detalle_empaque; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE detalle_empaque (
    id integer DEFAULT nextval('"detalle_empaque_Id_seq"'::regclass) NOT NULL,
    cantidad character varying(15) NOT NULL,
    insumo_id integer,
    empaque_id integer,
    fecha character varying(15)
);


ALTER TABLE detalle_empaque OWNER TO postgres;

--
-- Name: detalle_entrada_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "detalle_entrada_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "detalle_entrada_Id_seq" OWNER TO postgres;

--
-- Name: SEQUENCE "detalle_entrada_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "detalle_entrada_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- Name: detalle_entrada; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE detalle_entrada (
    id integer DEFAULT nextval('"detalle_entrada_Id_seq"'::regclass) NOT NULL,
    cantidad character varying(20) NOT NULL,
    valor character varying(15) NOT NULL,
    fecha_fabricacion character varying(30) NOT NULL,
    fecha_vencimiento character varying(30) NOT NULL,
    id_doc character varying(11),
    entrada_bodega_id integer,
    insumo_id integer
);


ALTER TABLE detalle_entrada OWNER TO postgres;

--
-- Name: detalle_ingreso_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "detalle_ingreso_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "detalle_ingreso_Id_seq" OWNER TO postgres;

--
-- Name: SEQUENCE "detalle_ingreso_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "detalle_ingreso_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- Name: detalle_ingreso; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE detalle_ingreso (
    id integer DEFAULT nextval('"detalle_ingreso_Id_seq"'::regclass) NOT NULL,
    cantidad character varying(20) NOT NULL,
    "procedencia_caña" character varying(30) NOT NULL,
    "peso_caña" character varying(20) NOT NULL,
    num_vagon character varying(20) NOT NULL,
    "ingreso_caña_id" integer,
    insumo_id integer
);


ALTER TABLE detalle_ingreso OWNER TO postgres;

--
-- Name: detalle_pago_trabajadores_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "detalle_pago_trabajadores_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "detalle_pago_trabajadores_Id_seq" OWNER TO postgres;

--
-- Name: SEQUENCE "detalle_pago_trabajadores_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "detalle_pago_trabajadores_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- Name: detalle_pago_trabajadores; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE detalle_pago_trabajadores (
    id integer DEFAULT nextval('"detalle_pago_trabajadores_Id_seq"'::regclass) NOT NULL,
    valor character varying(15) NOT NULL,
    pago_trabajores_id integer,
    empleado_id integer,
    tipo_pago_id integer
);


ALTER TABLE detalle_pago_trabajadores OWNER TO postgres;

--
-- Name: detalle_solicitud_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "detalle_solicitud_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "detalle_solicitud_Id_seq" OWNER TO postgres;

--
-- Name: SEQUENCE "detalle_solicitud_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "detalle_solicitud_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- Name: detalle_solicitud; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE detalle_solicitud (
    id integer DEFAULT nextval('"detalle_solicitud_Id_seq"'::regclass) NOT NULL,
    cantidad character varying(40) NOT NULL,
    fecha_fabricacion character varying(30) NOT NULL,
    fecha_vencimiento character varying(30) NOT NULL,
    insumo_id integer,
    solicitud_insumos_id integer
);


ALTER TABLE detalle_solicitud OWNER TO postgres;

--
-- Name: empaque_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "empaque_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "empaque_Id_seq" OWNER TO postgres;

--
-- Name: SEQUENCE "empaque_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "empaque_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- Name: empaque; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE empaque (
    id integer DEFAULT nextval('"empaque_Id_seq"'::regclass) NOT NULL,
    fecha character varying(30) NOT NULL,
    empleado_id integer,
    tipo_empaque_id integer
);


ALTER TABLE empaque OWNER TO postgres;

--
-- Name: empleado_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "empleado_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "empleado_Id_seq" OWNER TO postgres;

--
-- Name: SEQUENCE "empleado_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "empleado_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- Name: empleado; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE empleado (
    id integer DEFAULT nextval('"empleado_Id_seq"'::regclass) NOT NULL,
    nom_empleado character varying(50) NOT NULL,
    apell_empleado character varying(50) NOT NULL,
    direccion character varying(30) NOT NULL,
    tipo_id_id integer,
    credencial_id bigint,
    correo character varying(40),
    telefono bigint,
    numero_identificacion bigint
);


ALTER TABLE empleado OWNER TO postgres;

--
-- Name: empresa_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "empresa_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "empresa_Id_seq" OWNER TO postgres;

--
-- Name: SEQUENCE "empresa_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "empresa_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- Name: empresa; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE empresa (
    id integer DEFAULT nextval('"empresa_Id_seq"'::regclass) NOT NULL,
    nit character varying(20) NOT NULL,
    nom_empresa character varying(80) NOT NULL,
    razon_social character varying(60) NOT NULL,
    direccion character varying(50) NOT NULL,
    telefono character varying(15) NOT NULL,
    usuario_id character varying(11)
);


ALTER TABLE empresa OWNER TO postgres;

--
-- Name: entrada_bodega_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "entrada_bodega_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "entrada_bodega_Id_seq" OWNER TO postgres;

--
-- Name: SEQUENCE "entrada_bodega_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "entrada_bodega_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- Name: entrada_bodega; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE entrada_bodega (
    id integer DEFAULT nextval('"entrada_bodega_Id_seq"'::regclass) NOT NULL,
    fecha character varying(30) NOT NULL,
    proveedor_id integer
);


ALTER TABLE entrada_bodega OWNER TO postgres;

--
-- Name: ingreso_caña_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "ingreso_caña_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "ingreso_caña_Id_seq" OWNER TO postgres;

--
-- Name: SEQUENCE "ingreso_caña_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "ingreso_caña_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- Name: ingreso_caña; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE "ingreso_caña" (
    id integer DEFAULT nextval('"ingreso_caña_Id_seq"'::regclass) NOT NULL,
    fecha character varying(30) NOT NULL,
    empleado_id integer,
    proveedor_id integer
);


ALTER TABLE "ingreso_caña" OWNER TO postgres;

--
-- Name: insumo_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "insumo_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "insumo_Id_seq" OWNER TO postgres;

--
-- Name: SEQUENCE "insumo_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "insumo_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- Name: insumo; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE insumo (
    id integer DEFAULT nextval('"insumo_Id_seq"'::regclass) NOT NULL,
    desc_insumo character varying(30) NOT NULL,
    precio character varying(30) NOT NULL,
    tipo_insumo_id integer
);


ALTER TABLE insumo OWNER TO postgres;

--
-- Name: inventario_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "inventario_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "inventario_Id_seq" OWNER TO postgres;

--
-- Name: SEQUENCE "inventario_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "inventario_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- Name: inventario; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE inventario (
    id integer DEFAULT nextval('"inventario_Id_seq"'::regclass) NOT NULL,
    cantidad character varying(20) NOT NULL,
    saldo character varying(20) NOT NULL,
    tipo_doc_id integer,
    insumo_id integer
);


ALTER TABLE inventario OWNER TO postgres;

--
-- Name: pago_trabajores_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "pago_trabajores_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "pago_trabajores_Id_seq" OWNER TO postgres;

--
-- Name: SEQUENCE "pago_trabajores_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "pago_trabajores_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- Name: pago_trabajores; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE pago_trabajores (
    id integer DEFAULT nextval('"pago_trabajores_Id_seq"'::regclass) NOT NULL,
    fecha character varying(30) NOT NULL,
    periodo_inicio character varying(30) NOT NULL,
    periodo_fin character varying(30) NOT NULL,
    empresa_id integer
);


ALTER TABLE pago_trabajores OWNER TO postgres;

--
-- Name: proveedor_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "proveedor_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "proveedor_Id_seq" OWNER TO postgres;

--
-- Name: SEQUENCE "proveedor_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "proveedor_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- Name: proveedor; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE proveedor (
    id integer DEFAULT nextval('"proveedor_Id_seq"'::regclass) NOT NULL,
    razon_social character varying(30) NOT NULL,
    direccion character varying(30) NOT NULL,
    telefono character varying(15) NOT NULL,
    ciudad_id integer
);


ALTER TABLE proveedor OWNER TO postgres;

--
-- Name: recordar_me_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE recordar_me_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE recordar_me_id_seq OWNER TO postgres;

--
-- Name: SEQUENCE recordar_me_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE recordar_me_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- Name: recordar_me; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE recordar_me (
    id bigint DEFAULT nextval('recordar_me_id_seq'::regclass) NOT NULL,
    usuario_id bigint NOT NULL,
    ip_address character varying(50) NOT NULL,
    hash_cookie character varying(32) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE recordar_me OWNER TO postgres;

--
-- Name: solicitud_insumos_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "solicitud_insumos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "solicitud_insumos_Id_seq" OWNER TO postgres;

--
-- Name: SEQUENCE "solicitud_insumos_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "solicitud_insumos_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- Name: solicitud_insumos; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE solicitud_insumos (
    id integer DEFAULT nextval('"solicitud_insumos_Id_seq"'::regclass) NOT NULL,
    fecha character varying(30) NOT NULL,
    proveedor_id integer,
    empleado_id integer
);


ALTER TABLE solicitud_insumos OWNER TO postgres;

--
-- Name: tipo_doc_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "tipo_doc_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "tipo_doc_Id_seq" OWNER TO postgres;

--
-- Name: SEQUENCE "tipo_doc_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "tipo_doc_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- Name: tipo_doc; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE tipo_doc (
    id integer DEFAULT nextval('"tipo_doc_Id_seq"'::regclass) NOT NULL,
    desc_tipo_doc character varying(30) NOT NULL
);


ALTER TABLE tipo_doc OWNER TO postgres;

--
-- Name: tipo_empaque_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "tipo_empaque_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "tipo_empaque_Id_seq" OWNER TO postgres;

--
-- Name: SEQUENCE "tipo_empaque_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "tipo_empaque_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- Name: tipo_empaque; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE tipo_empaque (
    id integer DEFAULT nextval('"tipo_empaque_Id_seq"'::regclass) NOT NULL,
    desc_tipo_empaque character varying(40)
);


ALTER TABLE tipo_empaque OWNER TO postgres;

--
-- Name: tipo_id_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "tipo_id_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "tipo_id_Id_seq" OWNER TO postgres;

--
-- Name: SEQUENCE "tipo_id_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "tipo_id_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- Name: tipo_id; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE tipo_id (
    id integer DEFAULT nextval('"tipo_id_Id_seq"'::regclass) NOT NULL,
    desc_tipo_id character varying(50) NOT NULL
);


ALTER TABLE tipo_id OWNER TO postgres;

--
-- Name: tipo_insumo_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "tipo_insumo_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "tipo_insumo_Id_seq" OWNER TO postgres;

--
-- Name: SEQUENCE "tipo_insumo_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "tipo_insumo_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- Name: tipo_insumo; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE tipo_insumo (
    id integer DEFAULT nextval('"tipo_insumo_Id_seq"'::regclass) NOT NULL,
    desc_tipo_insumo character varying(80) NOT NULL
);


ALTER TABLE tipo_insumo OWNER TO postgres;

--
-- Name: tipo_pago_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "tipo_pago_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "tipo_pago_Id_seq" OWNER TO postgres;

--
-- Name: SEQUENCE "tipo_pago_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "tipo_pago_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- Name: tipo_pago; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE tipo_pago (
    id integer DEFAULT nextval('"tipo_pago_Id_seq"'::regclass) NOT NULL,
    desc_tipo_pago character varying(40) NOT NULL
);


ALTER TABLE tipo_pago OWNER TO postgres;

--
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE usuario_id_seq OWNER TO postgres;

--
-- Name: SEQUENCE usuario_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE usuario_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE usuario (
    id bigint DEFAULT nextval('usuario_id_seq'::regclass) NOT NULL,
    user_name character varying(80) NOT NULL,
    password character varying(32) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    last_login_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone
);


ALTER TABLE usuario OWNER TO postgres;

--
-- Name: COLUMN usuario.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN usuario.actived IS 'TRUE = activado | FALSE = desactivado';


--
-- Name: usuario_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "usuario_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "usuario_Id_seq" OWNER TO postgres;

--
-- Name: SEQUENCE "usuario_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "usuario_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- Name: usuario_credencial_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE usuario_credencial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE usuario_credencial_id_seq OWNER TO postgres;

--
-- Name: SEQUENCE usuario_credencial_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE usuario_credencial_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- Name: usuario_credencial; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE usuario_credencial (
    id bigint DEFAULT nextval('usuario_credencial_id_seq'::regclass) NOT NULL,
    usuario_id bigint NOT NULL,
    credencial_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE usuario_credencial OWNER TO postgres;

--
-- Name: usuario_credencial_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "usuario_credencial_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "usuario_credencial_Id_seq" OWNER TO postgres;

--
-- Name: SEQUENCE "usuario_credencial_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "usuario_credencial_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- Data for Name: bitacora; Type: TABLE DATA; Schema: public; Owner: postgres
--


--
-- Name: bitacora_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"bitacora_Id_seq"', 1, false);


--
-- Name: bitacora_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('bitacora_id_seq', 97, true);


--
-- Data for Name: ciudad; Type: TABLE DATA; Schema: public; Owner: postgres
--

--
-- Name: ciudad_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"ciudad_Id_seq"', 6, true);


--
-- Data for Name: control_calidad; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Name: control_calidad_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"control_calidad_Id_seq"', 16, true);


--
-- Data for Name: credencial; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Name: credencial_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"credencial_Id_seq"', 1, false);


--
-- Name: credencial_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('credencial_id_seq', 4, true);


--
-- Name: dato_usuario_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"dato_usuario_Id_seq"', 1, false);


--
-- Data for Name: detalle_empaque; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Name: detalle_empaque_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"detalle_empaque_Id_seq"', 1, false);


--
-- Data for Name: detalle_entrada; Type: TABLE DATA; Schema: public; Owner: postgres
--




--
-- Name: detalle_entrada_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"detalle_entrada_Id_seq"', 1, false);


--
-- Data for Name: detalle_ingreso; Type: TABLE DATA; Schema: public; Owner: postgres
--


--
-- Name: detalle_ingreso_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"detalle_ingreso_Id_seq"', 1, false);


--
-- Data for Name: detalle_pago_trabajadores; Type: TABLE DATA; Schema: public; Owner: postgres
--




--
-- Name: detalle_pago_trabajadores_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"detalle_pago_trabajadores_Id_seq"', 1, false);


--
-- Data for Name: detalle_solicitud; Type: TABLE DATA; Schema: public; Owner: postgres
--




--
-- Name: detalle_solicitud_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"detalle_solicitud_Id_seq"', 1, false);


--
-- Data for Name: empaque; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Name: empaque_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"empaque_Id_seq"', 2, true);


--
-- Data for Name: empleado; Type: TABLE DATA; Schema: public; Owner: postgres
--




--
-- Name: empleado_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"empleado_Id_seq"', 5, true);


--
-- Data for Name: empresa; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Name: empresa_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"empresa_Id_seq"', 1, false);


--
-- Data for Name: entrada_bodega; Type: TABLE DATA; Schema: public; Owner: postgres
--




--
-- Name: entrada_bodega_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"entrada_bodega_Id_seq"', 1, false);


--
-- Data for Name: ingreso_caña; Type: TABLE DATA; Schema: public; Owner: postgres
--




--
-- Name: ingreso_caña_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"ingreso_caña_Id_seq"', 1, false);


--
-- Data for Name: insumo; Type: TABLE DATA; Schema: public; Owner: postgres
--




--
-- Name: insumo_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"insumo_Id_seq"', 3, true);


--
-- Data for Name: inventario; Type: TABLE DATA; Schema: public; Owner: postgres
--




--
-- Name: inventario_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"inventario_Id_seq"', 1, false);


--
-- Data for Name: pago_trabajores; Type: TABLE DATA; Schema: public; Owner: postgres
--




--
-- Name: pago_trabajores_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"pago_trabajores_Id_seq"', 1, false);


--
-- Data for Name: proveedor; Type: TABLE DATA; Schema: public; Owner: postgres
--




--
-- Name: proveedor_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"proveedor_Id_seq"', 4, true);


--
-- Data for Name: recordar_me; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Name: recordar_me_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('recordar_me_id_seq', 7, true);


--
-- Data for Name: solicitud_insumos; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Name: solicitud_insumos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"solicitud_insumos_Id_seq"', 1, false);


--
-- Data for Name: tipo_doc; Type: TABLE DATA; Schema: public; Owner: postgres
--




--
-- Name: tipo_doc_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"tipo_doc_Id_seq"', 1, false);


--
-- Data for Name: tipo_empaque; Type: TABLE DATA; Schema: public; Owner: postgres
--




--
-- Name: tipo_empaque_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"tipo_empaque_Id_seq"', 4, true);


--
-- Data for Name: tipo_id; Type: TABLE DATA; Schema: public; Owner: postgres
--




--
-- Name: tipo_id_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"tipo_id_Id_seq"', 3, true);


--
-- Data for Name: tipo_insumo; Type: TABLE DATA; Schema: public; Owner: postgres
--




--
-- Name: tipo_insumo_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"tipo_insumo_Id_seq"', 1, true);


--
-- Data for Name: tipo_pago; Type: TABLE DATA; Schema: public; Owner: postgres
--




--
-- Name: tipo_pago_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"tipo_pago_Id_seq"', 1, false);


--
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Name: usuario_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"usuario_Id_seq"', 1, false);


--
-- Data for Name: usuario_credencial; Type: TABLE DATA; Schema: public; Owner: postgres
--




--
-- Name: usuario_credencial_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"usuario_credencial_Id_seq"', 1, false);


--
-- Name: usuario_credencial_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('usuario_credencial_id_seq', 1, true);


--
-- Name: usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('usuario_id_seq', 22, true);


--
-- Name: pkbitacora; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY bitacora
    ADD CONSTRAINT pkbitacora PRIMARY KEY (id);


--
-- Name: pkciudad; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY ciudad
    ADD CONSTRAINT pkciudad PRIMARY KEY (id);


--
-- Name: pkcontrol_calidad; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY control_calidad
    ADD CONSTRAINT pkcontrol_calidad PRIMARY KEY (id);


--
-- Name: pkcredencial; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY credencial
    ADD CONSTRAINT pkcredencial PRIMARY KEY (id);


--
-- Name: pkdetalle_empaque; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY detalle_empaque
    ADD CONSTRAINT pkdetalle_empaque PRIMARY KEY (id);


--
-- Name: pkdetalle_entrada; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY detalle_entrada
    ADD CONSTRAINT pkdetalle_entrada PRIMARY KEY (id);


--
-- Name: pkdetalle_ingreso; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY detalle_ingreso
    ADD CONSTRAINT pkdetalle_ingreso PRIMARY KEY (id);


--
-- Name: pkdetalle_pago_trabajadores; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY detalle_pago_trabajadores
    ADD CONSTRAINT pkdetalle_pago_trabajadores PRIMARY KEY (id);


--
-- Name: pkdetalle_solicitud; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY detalle_solicitud
    ADD CONSTRAINT pkdetalle_solicitud PRIMARY KEY (id);


--
-- Name: pkempaque; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY empaque
    ADD CONSTRAINT pkempaque PRIMARY KEY (id);


--
-- Name: pkempleado; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY empleado
    ADD CONSTRAINT pkempleado PRIMARY KEY (id);


--
-- Name: pkempresa; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY empresa
    ADD CONSTRAINT pkempresa PRIMARY KEY (id);


--
-- Name: pkentrada_bodega; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY entrada_bodega
    ADD CONSTRAINT pkentrada_bodega PRIMARY KEY (id);


--
-- Name: pkingreso_caña; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY "ingreso_caña"
    ADD CONSTRAINT "pkingreso_caña" PRIMARY KEY (id);


--
-- Name: pkinsumo; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY insumo
    ADD CONSTRAINT pkinsumo PRIMARY KEY (id);


--
-- Name: pkinventario; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY inventario
    ADD CONSTRAINT pkinventario PRIMARY KEY (id);


--
-- Name: pkpago_trabajores; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY pago_trabajores
    ADD CONSTRAINT pkpago_trabajores PRIMARY KEY (id);


--
-- Name: pkproveedor; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY proveedor
    ADD CONSTRAINT pkproveedor PRIMARY KEY (id);


--
-- Name: pkrecordar_me; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY recordar_me
    ADD CONSTRAINT pkrecordar_me PRIMARY KEY (id);


--
-- Name: pksolicitud_insumos; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY solicitud_insumos
    ADD CONSTRAINT pksolicitud_insumos PRIMARY KEY (id);


--
-- Name: pktipo_doc; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY tipo_doc
    ADD CONSTRAINT pktipo_doc PRIMARY KEY (id);


--
-- Name: pktipo_empaque; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY tipo_empaque
    ADD CONSTRAINT pktipo_empaque PRIMARY KEY (id);


--
-- Name: pktipo_id; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY tipo_id
    ADD CONSTRAINT pktipo_id PRIMARY KEY (id);


--
-- Name: pktipo_insumo; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY tipo_insumo
    ADD CONSTRAINT pktipo_insumo PRIMARY KEY (id);


--
-- Name: pktipo_pago; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY tipo_pago
    ADD CONSTRAINT pktipo_pago PRIMARY KEY (id);


--
-- Name: pkusuario; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY usuario
    ADD CONSTRAINT pkusuario PRIMARY KEY (id);


--
-- Name: pkusuario_credencial; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT pkusuario_credencial PRIMARY KEY (id);


--
-- Name: bitacora_fecha_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "bitacora_fecha_Idx" ON bitacora USING btree (fecha);


--
-- Name: bitacora_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "bitacora_usuario_id_Idx" ON bitacora USING btree (usuario_id);


--
-- Name: recordar_me_ip_address_hash_cookie_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "recordar_me_ip_address_hash_cookie_Idx" ON recordar_me USING btree (ip_address, hash_cookie);


--
-- Name: recordar_me_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "recordar_me_usuario_id_Idx" ON recordar_me USING btree (usuario_id);


--
-- Name: usuario_actived_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_actived_Idx" ON usuario USING btree (actived);


--
-- Name: usuario_credencial_credencial_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_credencial_credencial_id_Idx" ON usuario_credencial USING btree (credencial_id);


--
-- Name: usuario_credencial_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_credencial_usuario_id_Idx" ON usuario_credencial USING btree (usuario_id);


--
-- Name: usuario_credencial_usuario_id_credencial_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "usuario_credencial_usuario_id_credencial_id_Idx" ON usuario_credencial USING btree (usuario_id, credencial_id);


--
-- Name: usuario_deleted_at_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_deleted_at_Idx" ON usuario USING btree (deleted_at);


--
-- Name: usuario_user_name_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "usuario_user_name_Idx" ON usuario USING btree (user_name);


--
-- Name: usuario_user_name_password_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_user_name_password_Idx" ON usuario USING btree (user_name, password);


--
-- Name: fk_bitacora_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY bitacora
    ADD CONSTRAINT fk_bitacora_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: fk_control_calidad_empleado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY control_calidad
    ADD CONSTRAINT fk_control_calidad_empleado FOREIGN KEY (empleado_id) REFERENCES empleado(id);


--
-- Name: fk_control_calidad_proveedor; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY control_calidad
    ADD CONSTRAINT fk_control_calidad_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedor(id);


--
-- Name: fk_detalle_empaque_empaque; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_empaque
    ADD CONSTRAINT fk_detalle_empaque_empaque FOREIGN KEY (empaque_id) REFERENCES empaque(id);


--
-- Name: fk_detalle_empaque_insumo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_empaque
    ADD CONSTRAINT fk_detalle_empaque_insumo FOREIGN KEY (insumo_id) REFERENCES insumo(id);


--
-- Name: fk_detalle_entrada_entrada_bodega; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_entrada
    ADD CONSTRAINT fk_detalle_entrada_entrada_bodega FOREIGN KEY (entrada_bodega_id) REFERENCES entrada_bodega(id);


--
-- Name: fk_detalle_entrada_insumo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_entrada
    ADD CONSTRAINT fk_detalle_entrada_insumo FOREIGN KEY (insumo_id) REFERENCES insumo(id);


--
-- Name: fk_detalle_ingreso_ingreso_caña; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_ingreso
    ADD CONSTRAINT "fk_detalle_ingreso_ingreso_caña" FOREIGN KEY ("ingreso_caña_id") REFERENCES "ingreso_caña"(id);


--
-- Name: fk_detalle_ingreso_insumo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_ingreso
    ADD CONSTRAINT fk_detalle_ingreso_insumo FOREIGN KEY (insumo_id) REFERENCES insumo(id);


--
-- Name: fk_detalle_pago_trabajadores_empleado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_pago_trabajadores
    ADD CONSTRAINT fk_detalle_pago_trabajadores_empleado FOREIGN KEY (empleado_id) REFERENCES empleado(id);


--
-- Name: fk_detalle_pago_trabajadores_pago_trabajores; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_pago_trabajadores
    ADD CONSTRAINT fk_detalle_pago_trabajadores_pago_trabajores FOREIGN KEY (pago_trabajores_id) REFERENCES pago_trabajores(id);


--
-- Name: fk_detalle_pago_trabajadores_tipo_pago; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_pago_trabajadores
    ADD CONSTRAINT fk_detalle_pago_trabajadores_tipo_pago FOREIGN KEY (tipo_pago_id) REFERENCES tipo_pago(id);


--
-- Name: fk_detalle_solicitud_insumo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_solicitud
    ADD CONSTRAINT fk_detalle_solicitud_insumo FOREIGN KEY (insumo_id) REFERENCES insumo(id);


--
-- Name: fk_detalle_solicitud_solicitud_insumos; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_solicitud
    ADD CONSTRAINT fk_detalle_solicitud_solicitud_insumos FOREIGN KEY (solicitud_insumos_id) REFERENCES solicitud_insumos(id);


--
-- Name: fk_empaque_empleado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY empaque
    ADD CONSTRAINT fk_empaque_empleado FOREIGN KEY (empleado_id) REFERENCES empleado(id);


--
-- Name: fk_empaque_tipo_empaque; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY empaque
    ADD CONSTRAINT fk_empaque_tipo_empaque FOREIGN KEY (tipo_empaque_id) REFERENCES tipo_empaque(id);


--
-- Name: fk_empleado_credencial; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY empleado
    ADD CONSTRAINT fk_empleado_credencial FOREIGN KEY (credencial_id) REFERENCES credencial(id);


--
-- Name: fk_empleado_tipo_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY empleado
    ADD CONSTRAINT fk_empleado_tipo_id FOREIGN KEY (tipo_id_id) REFERENCES tipo_id(id);


--
-- Name: fk_entrada_bodega_proveedor; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY entrada_bodega
    ADD CONSTRAINT fk_entrada_bodega_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedor(id);


--
-- Name: fk_ingreso_caña_empleado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "ingreso_caña"
    ADD CONSTRAINT "fk_ingreso_caña_empleado" FOREIGN KEY (empleado_id) REFERENCES empleado(id);


--
-- Name: fk_ingreso_caña_proveedor; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "ingreso_caña"
    ADD CONSTRAINT "fk_ingreso_caña_proveedor" FOREIGN KEY (proveedor_id) REFERENCES proveedor(id);


--
-- Name: fk_insumo_tipo_insumo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY insumo
    ADD CONSTRAINT fk_insumo_tipo_insumo FOREIGN KEY (tipo_insumo_id) REFERENCES tipo_insumo(id);


--
-- Name: fk_inventario_insumo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY inventario
    ADD CONSTRAINT fk_inventario_insumo FOREIGN KEY (insumo_id) REFERENCES insumo(id);


--
-- Name: fk_inventario_tipo_doc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY inventario
    ADD CONSTRAINT fk_inventario_tipo_doc FOREIGN KEY (tipo_doc_id) REFERENCES tipo_doc(id);


--
-- Name: fk_pago_trabajores_empresa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY pago_trabajores
    ADD CONSTRAINT fk_pago_trabajores_empresa FOREIGN KEY (empresa_id) REFERENCES empresa(id);


--
-- Name: fk_proveedor_ciudad; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY proveedor
    ADD CONSTRAINT fk_proveedor_ciudad FOREIGN KEY (ciudad_id) REFERENCES ciudad(id);


--
-- Name: fk_recordar_me_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY recordar_me
    ADD CONSTRAINT fk_recordar_me_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: fk_solicitud_insumos_empleado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY solicitud_insumos
    ADD CONSTRAINT fk_solicitud_insumos_empleado FOREIGN KEY (empleado_id) REFERENCES empleado(id);


--
-- Name: fk_solicitud_insumos_proveedor; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY solicitud_insumos
    ADD CONSTRAINT fk_solicitud_insumos_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedor(id);


--
-- Name: fk_usuario_credencial_credencial; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT fk_usuario_credencial_credencial FOREIGN KEY (credencial_id) REFERENCES credencial(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: fk_usuario_credencial_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT fk_usuario_credencial_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;



-- ----------------------------
--  Records of "credencial"
-- ----------------------------
BEGIN;
INSERT INTO "credencial" (nombre) VALUES ('admin');
INSERT INTO "credencial" (nombre) VALUES ('usuario');
COMMIT;

-- ----------------------------
--  Records of "usuario" admin - 123
-- ----------------------------
BEGIN;
INSERT INTO "usuario" (user_name, password, actived, last_login_at) VALUES ('admin', '202cb962ac59075b964b07152d234b70', 't', null);
COMMIT;

-- ----------------------------
--  Records of "usuario_credencial"
-- ----------------------------
BEGIN;
INSERT INTO "usuario_credencial" (usuario_id, credencial_id) VALUES (1, 1);
COMMIT;
--
-- Name: public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM postgres;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

