--
-- PostgreSQL database dump
--

-- Dumped from database version 9.3.4
-- Dumped by pg_dump version 9.4.0
-- Started on 2015-02-26 14:30:42

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

--
-- TOC entry 226 (class 3079 OID 11750)
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- TOC entry 2271 (class 0 OID 0)
-- Dependencies: 226
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


SET search_path = public, pg_catalog;

--
-- TOC entry 170 (class 1259 OID 32769)
-- Name: bitacora_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE bitacora_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE bitacora_id_seq OWNER TO postgres;

--
-- TOC entry 2272 (class 0 OID 0)
-- Dependencies: 170
-- Name: SEQUENCE bitacora_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE bitacora_id_seq IS 'DbWrench Autogenerated Sequence.';


SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 175 (class 1259 OID 32779)
-- Name: bitacora; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE bitacora (
    id bigint DEFAULT nextval('bitacora_id_seq'::regclass) NOT NULL,
    usuario_id bigint NOT NULL,
    accion character varying(80) NOT NULL,
    tabla character varying(80) NOT NULL,
    registro bigint,
    observacion character varying(1024),
    fecha timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE bitacora OWNER TO postgres;

--
-- TOC entry 180 (class 1259 OID 32872)
-- Name: bitacora_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "bitacora_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "bitacora_Id_seq" OWNER TO postgres;

--
-- TOC entry 2273 (class 0 OID 0)
-- Dependencies: 180
-- Name: SEQUENCE "bitacora_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "bitacora_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 181 (class 1259 OID 32874)
-- Name: ciudad_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "ciudad_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "ciudad_Id_seq" OWNER TO postgres;

--
-- TOC entry 2274 (class 0 OID 0)
-- Dependencies: 181
-- Name: SEQUENCE "ciudad_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "ciudad_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 182 (class 1259 OID 32876)
-- Name: control_calidad_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "control_calidad_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "control_calidad_Id_seq" OWNER TO postgres;

--
-- TOC entry 2275 (class 0 OID 0)
-- Dependencies: 182
-- Name: SEQUENCE "control_calidad_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "control_calidad_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 206 (class 1259 OID 32925)
-- Name: control_calidad; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE control_calidad (
    "Id" integer DEFAULT nextval('"control_calidad_Id_seq"'::regclass) NOT NULL,
    fecha character varying(30) NOT NULL,
    turno character varying(10) NOT NULL,
    brix character varying(10) NOT NULL,
    ph character varying(10) NOT NULL,
    ar character varying(10) NOT NULL,
    sacarosa character varying(15) NOT NULL,
    pureza character varying(20) NOT NULL,
    id_empleado character varying(15),
    id_proveedor character varying(15),
    "empleado_Id" integer,
    "proveedor_Id" integer
);


ALTER TABLE control_calidad OWNER TO postgres;

--
-- TOC entry 171 (class 1259 OID 32771)
-- Name: credencial_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE credencial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE credencial_id_seq OWNER TO postgres;

--
-- TOC entry 2276 (class 0 OID 0)
-- Dependencies: 171
-- Name: SEQUENCE credencial_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE credencial_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 176 (class 1259 OID 32791)
-- Name: credencial; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE credencial (
    id bigint DEFAULT nextval('credencial_id_seq'::regclass) NOT NULL,
    nombre character varying(80) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone
);


ALTER TABLE credencial OWNER TO postgres;

--
-- TOC entry 183 (class 1259 OID 32878)
-- Name: credencial_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "credencial_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "credencial_Id_seq" OWNER TO postgres;

--
-- TOC entry 2277 (class 0 OID 0)
-- Dependencies: 183
-- Name: SEQUENCE "credencial_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "credencial_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 184 (class 1259 OID 32880)
-- Name: dato_usuario_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "dato_usuario_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "dato_usuario_Id_seq" OWNER TO postgres;

--
-- TOC entry 2278 (class 0 OID 0)
-- Dependencies: 184
-- Name: SEQUENCE "dato_usuario_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "dato_usuario_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 185 (class 1259 OID 32882)
-- Name: detalle_empaque_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "detalle_empaque_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "detalle_empaque_Id_seq" OWNER TO postgres;

--
-- TOC entry 2279 (class 0 OID 0)
-- Dependencies: 185
-- Name: SEQUENCE "detalle_empaque_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "detalle_empaque_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 207 (class 1259 OID 32931)
-- Name: detalle_empaque; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE detalle_empaque (
    "Id" integer DEFAULT nextval('"detalle_empaque_Id_seq"'::regclass) NOT NULL,
    cantidad character varying(15) NOT NULL,
    id_insumo character varying(11),
    id_empaque character varying(11),
    "insumo_Id" integer,
    "empaque_Id" integer
);


ALTER TABLE detalle_empaque OWNER TO postgres;

--
-- TOC entry 186 (class 1259 OID 32884)
-- Name: detalle_entrada_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "detalle_entrada_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "detalle_entrada_Id_seq" OWNER TO postgres;

--
-- TOC entry 2280 (class 0 OID 0)
-- Dependencies: 186
-- Name: SEQUENCE "detalle_entrada_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "detalle_entrada_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 208 (class 1259 OID 32937)
-- Name: detalle_entrada; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE detalle_entrada (
    "Id" integer DEFAULT nextval('"detalle_entrada_Id_seq"'::regclass) NOT NULL,
    cantidad character varying(20) NOT NULL,
    valor character varying(15) NOT NULL,
    fecha_fabricacion character varying(30) NOT NULL,
    fecha_vencimiento character varying(30) NOT NULL,
    id_doc character varying(11),
    id_insumo character varying(11),
    "entrada_bodega_Id" integer,
    "insumo_Id" integer
);


ALTER TABLE detalle_entrada OWNER TO postgres;

--
-- TOC entry 187 (class 1259 OID 32886)
-- Name: detalle_ingreso_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "detalle_ingreso_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "detalle_ingreso_Id_seq" OWNER TO postgres;

--
-- TOC entry 2281 (class 0 OID 0)
-- Dependencies: 187
-- Name: SEQUENCE "detalle_ingreso_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "detalle_ingreso_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 209 (class 1259 OID 32943)
-- Name: detalle_ingreso; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE detalle_ingreso (
    "Id" integer DEFAULT nextval('"detalle_ingreso_Id_seq"'::regclass) NOT NULL,
    cantidad character varying(20) NOT NULL,
    "procedencia_caña" character varying(30) NOT NULL,
    "peso_caña" character varying(20) NOT NULL,
    num_vagon character varying(20) NOT NULL,
    id_ingreso character varying(11),
    id_insumo character varying(11),
    "ingreso_caña_Id" integer,
    "insumo_Id" integer
);


ALTER TABLE detalle_ingreso OWNER TO postgres;

--
-- TOC entry 188 (class 1259 OID 32888)
-- Name: detalle_pago_trabajadores_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "detalle_pago_trabajadores_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "detalle_pago_trabajadores_Id_seq" OWNER TO postgres;

--
-- TOC entry 2282 (class 0 OID 0)
-- Dependencies: 188
-- Name: SEQUENCE "detalle_pago_trabajadores_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "detalle_pago_trabajadores_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 210 (class 1259 OID 32949)
-- Name: detalle_pago_trabajadores; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE detalle_pago_trabajadores (
    "Id" integer DEFAULT nextval('"detalle_pago_trabajadores_Id_seq"'::regclass) NOT NULL,
    valor character varying(15) NOT NULL,
    id_pago_trabajadores character varying(11),
    id_empleado character varying(11),
    id_tipo_pago character varying(11),
    "pago_trabajores_Id" integer,
    "empleado_Id" integer,
    "tipo_pago_Id" integer
);


ALTER TABLE detalle_pago_trabajadores OWNER TO postgres;

--
-- TOC entry 189 (class 1259 OID 32890)
-- Name: detalle_solicitud_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "detalle_solicitud_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "detalle_solicitud_Id_seq" OWNER TO postgres;

--
-- TOC entry 2283 (class 0 OID 0)
-- Dependencies: 189
-- Name: SEQUENCE "detalle_solicitud_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "detalle_solicitud_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 211 (class 1259 OID 32955)
-- Name: detalle_solicitud; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE detalle_solicitud (
    "Id" integer DEFAULT nextval('"detalle_solicitud_Id_seq"'::regclass) NOT NULL,
    cantidad character varying(40) NOT NULL,
    fecha_fabricacion character varying(30) NOT NULL,
    fecha_vencimiento character varying(30) NOT NULL,
    id_solicitud character varying(11),
    id_insumo character varying(11),
    "insumo_Id" integer,
    "solicitud_insumos_Id" integer
);


ALTER TABLE detalle_solicitud OWNER TO postgres;

--
-- TOC entry 190 (class 1259 OID 32892)
-- Name: empaque_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "empaque_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "empaque_Id_seq" OWNER TO postgres;

--
-- TOC entry 2284 (class 0 OID 0)
-- Dependencies: 190
-- Name: SEQUENCE "empaque_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "empaque_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 212 (class 1259 OID 32961)
-- Name: empaque; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE empaque (
    "Id" integer DEFAULT nextval('"empaque_Id_seq"'::regclass) NOT NULL,
    id_empleado character varying(15),
    fecha character varying(30) NOT NULL,
    "empleado_Id" integer
);


ALTER TABLE empaque OWNER TO postgres;

--
-- TOC entry 191 (class 1259 OID 32894)
-- Name: empleado_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "empleado_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "empleado_Id_seq" OWNER TO postgres;

--
-- TOC entry 2285 (class 0 OID 0)
-- Dependencies: 191
-- Name: SEQUENCE "empleado_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "empleado_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 213 (class 1259 OID 32967)
-- Name: empleado; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE empleado (
    "Id" integer DEFAULT nextval('"empleado_Id_seq"'::regclass) NOT NULL,
    nom_empleado character varying(50) NOT NULL,
    apell_empleado character varying(50) NOT NULL,
    telefono character varying(15) NOT NULL,
    direccion character varying(30) NOT NULL,
    id_tipo_id character varying(10),
    "tipo_id_Id" integer
);


ALTER TABLE empleado OWNER TO postgres;

--
-- TOC entry 192 (class 1259 OID 32896)
-- Name: empresa_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "empresa_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "empresa_Id_seq" OWNER TO postgres;

--
-- TOC entry 2286 (class 0 OID 0)
-- Dependencies: 192
-- Name: SEQUENCE "empresa_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "empresa_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 214 (class 1259 OID 32973)
-- Name: empresa; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE empresa (
    "Id" integer DEFAULT nextval('"empresa_Id_seq"'::regclass) NOT NULL,
    nit character varying(20) NOT NULL,
    nom_empresa character varying(80) NOT NULL,
    razon_social character varying(60) NOT NULL,
    direccion character varying(50) NOT NULL,
    telefono character varying(15) NOT NULL,
    usuario_id character varying(11)
);


ALTER TABLE empresa OWNER TO postgres;

--
-- TOC entry 193 (class 1259 OID 32898)
-- Name: entrada_bodega_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "entrada_bodega_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "entrada_bodega_Id_seq" OWNER TO postgres;

--
-- TOC entry 2287 (class 0 OID 0)
-- Dependencies: 193
-- Name: SEQUENCE "entrada_bodega_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "entrada_bodega_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 215 (class 1259 OID 32979)
-- Name: entrada_bodega; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE entrada_bodega (
    "Id" integer DEFAULT nextval('"entrada_bodega_Id_seq"'::regclass) NOT NULL,
    fecha character varying(30) NOT NULL,
    id_proveedor character varying(15),
    "proveedor_Id" integer
);


ALTER TABLE entrada_bodega OWNER TO postgres;

--
-- TOC entry 194 (class 1259 OID 32900)
-- Name: ingreso_caña_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "ingreso_caña_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "ingreso_caña_Id_seq" OWNER TO postgres;

--
-- TOC entry 2288 (class 0 OID 0)
-- Dependencies: 194
-- Name: SEQUENCE "ingreso_caña_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "ingreso_caña_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 216 (class 1259 OID 32985)
-- Name: ingreso_caña; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE "ingreso_caña" (
    "Id" integer DEFAULT nextval('"ingreso_caña_Id_seq"'::regclass) NOT NULL,
    fecha character varying(30) NOT NULL,
    id_proveedor character varying(11),
    id_empleado character varying(11),
    "empleado_Id" integer,
    "proveedor_Id" integer
);


ALTER TABLE "ingreso_caña" OWNER TO postgres;

--
-- TOC entry 195 (class 1259 OID 32902)
-- Name: insumo_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "insumo_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "insumo_Id_seq" OWNER TO postgres;

--
-- TOC entry 2289 (class 0 OID 0)
-- Dependencies: 195
-- Name: SEQUENCE "insumo_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "insumo_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 217 (class 1259 OID 32991)
-- Name: insumo; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE insumo (
    "Id" integer DEFAULT nextval('"insumo_Id_seq"'::regclass) NOT NULL,
    desc_insumo character varying(30) NOT NULL,
    precio character varying(30) NOT NULL,
    id_tipo_insumo character varying(11),
    "tipo_insumo_Id" integer
);


ALTER TABLE insumo OWNER TO postgres;

--
-- TOC entry 196 (class 1259 OID 32904)
-- Name: inventario_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "inventario_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "inventario_Id_seq" OWNER TO postgres;

--
-- TOC entry 2290 (class 0 OID 0)
-- Dependencies: 196
-- Name: SEQUENCE "inventario_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "inventario_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 218 (class 1259 OID 32997)
-- Name: inventario; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE inventario (
    "Id" integer DEFAULT nextval('"inventario_Id_seq"'::regclass) NOT NULL,
    cantidad character varying(20) NOT NULL,
    saldo character varying(20) NOT NULL,
    id_tipo_doc character varying(11),
    id_insumo character varying(11),
    "tipo_doc_Id" integer,
    "insumo_Id" integer
);


ALTER TABLE inventario OWNER TO postgres;

--
-- TOC entry 197 (class 1259 OID 32906)
-- Name: pago_trabajores_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "pago_trabajores_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "pago_trabajores_Id_seq" OWNER TO postgres;

--
-- TOC entry 2291 (class 0 OID 0)
-- Dependencies: 197
-- Name: SEQUENCE "pago_trabajores_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "pago_trabajores_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 219 (class 1259 OID 33003)
-- Name: pago_trabajores; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE pago_trabajores (
    "Id" integer DEFAULT nextval('"pago_trabajores_Id_seq"'::regclass) NOT NULL,
    fecha character varying(30) NOT NULL,
    periodo_inicio character varying(30) NOT NULL,
    periodo_fin character varying(30) NOT NULL,
    id_empresa character varying(11) NOT NULL,
    "empresa_Id" integer
);


ALTER TABLE pago_trabajores OWNER TO postgres;

--
-- TOC entry 198 (class 1259 OID 32908)
-- Name: proveedor_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "proveedor_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "proveedor_Id_seq" OWNER TO postgres;

--
-- TOC entry 2292 (class 0 OID 0)
-- Dependencies: 198
-- Name: SEQUENCE "proveedor_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "proveedor_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 220 (class 1259 OID 33009)
-- Name: proveedor; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE proveedor (
    "Id" integer DEFAULT nextval('"proveedor_Id_seq"'::regclass) NOT NULL,
    razon_social character varying(30) NOT NULL,
    direccion character varying(30) NOT NULL,
    telefono character varying(15) NOT NULL,
    id_ciudad character varying(10),
    "ciudad_Id" integer
);


ALTER TABLE proveedor OWNER TO postgres;

--
-- TOC entry 172 (class 1259 OID 32773)
-- Name: recordar_me_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE recordar_me_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE recordar_me_id_seq OWNER TO postgres;

--
-- TOC entry 2293 (class 0 OID 0)
-- Dependencies: 172
-- Name: SEQUENCE recordar_me_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE recordar_me_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 177 (class 1259 OID 32799)
-- Name: recordar_me; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE recordar_me (
    id bigint DEFAULT nextval('recordar_me_id_seq'::regclass) NOT NULL,
    usuario_id bigint NOT NULL,
    ip_address character varying(50) NOT NULL,
    hash_cookie character varying(32) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE recordar_me OWNER TO postgres;

--
-- TOC entry 199 (class 1259 OID 32910)
-- Name: solicitud_insumos_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "solicitud_insumos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "solicitud_insumos_Id_seq" OWNER TO postgres;

--
-- TOC entry 2294 (class 0 OID 0)
-- Dependencies: 199
-- Name: SEQUENCE "solicitud_insumos_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "solicitud_insumos_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 221 (class 1259 OID 33015)
-- Name: solicitud_insumos; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE solicitud_insumos (
    "Id" integer DEFAULT nextval('"solicitud_insumos_Id_seq"'::regclass) NOT NULL,
    fecha character varying(30) NOT NULL,
    id_proveedor character varying(11),
    id_empleado character varying(11),
    "proveedor_Id" integer,
    "empleado_Id" integer
);


ALTER TABLE solicitud_insumos OWNER TO postgres;

--
-- TOC entry 200 (class 1259 OID 32912)
-- Name: tipo_doc_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "tipo_doc_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "tipo_doc_Id_seq" OWNER TO postgres;

--
-- TOC entry 2295 (class 0 OID 0)
-- Dependencies: 200
-- Name: SEQUENCE "tipo_doc_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "tipo_doc_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 222 (class 1259 OID 33021)
-- Name: tipo_doc; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE tipo_doc (
    "Id" integer DEFAULT nextval('"tipo_doc_Id_seq"'::regclass) NOT NULL,
    desc_tipo_doc character varying(30) NOT NULL
);


ALTER TABLE tipo_doc OWNER TO postgres;

--
-- TOC entry 201 (class 1259 OID 32914)
-- Name: tipo_id_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "tipo_id_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "tipo_id_Id_seq" OWNER TO postgres;

--
-- TOC entry 2296 (class 0 OID 0)
-- Dependencies: 201
-- Name: SEQUENCE "tipo_id_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "tipo_id_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 223 (class 1259 OID 33027)
-- Name: tipo_id; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE tipo_id (
    "Id" integer DEFAULT nextval('"tipo_id_Id_seq"'::regclass) NOT NULL,
    desc_tipo_id character varying(50) NOT NULL
);


ALTER TABLE tipo_id OWNER TO postgres;

--
-- TOC entry 202 (class 1259 OID 32916)
-- Name: tipo_insumo_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "tipo_insumo_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "tipo_insumo_Id_seq" OWNER TO postgres;

--
-- TOC entry 2297 (class 0 OID 0)
-- Dependencies: 202
-- Name: SEQUENCE "tipo_insumo_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "tipo_insumo_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 224 (class 1259 OID 33033)
-- Name: tipo_insumo; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE tipo_insumo (
    "Id" integer DEFAULT nextval('"tipo_insumo_Id_seq"'::regclass) NOT NULL,
    desc_tipo_insumo character varying(80) NOT NULL
);


ALTER TABLE tipo_insumo OWNER TO postgres;

--
-- TOC entry 203 (class 1259 OID 32918)
-- Name: tipo_pago_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "tipo_pago_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "tipo_pago_Id_seq" OWNER TO postgres;

--
-- TOC entry 2298 (class 0 OID 0)
-- Dependencies: 203
-- Name: SEQUENCE "tipo_pago_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "tipo_pago_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 225 (class 1259 OID 33039)
-- Name: tipo_pago; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE tipo_pago (
    "Id" integer DEFAULT nextval('"tipo_pago_Id_seq"'::regclass) NOT NULL,
    desc_tipo_pago character varying(40) NOT NULL
);


ALTER TABLE tipo_pago OWNER TO postgres;

--
-- TOC entry 173 (class 1259 OID 32775)
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE usuario_id_seq OWNER TO postgres;

--
-- TOC entry 2299 (class 0 OID 0)
-- Dependencies: 173
-- Name: SEQUENCE usuario_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE usuario_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 178 (class 1259 OID 32808)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE usuario (
    id bigint DEFAULT nextval('usuario_id_seq'::regclass) NOT NULL,
    user_name character varying(80) NOT NULL,
    password character varying(32) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    last_login_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone
);


ALTER TABLE usuario OWNER TO postgres;

--
-- TOC entry 2300 (class 0 OID 0)
-- Dependencies: 178
-- Name: COLUMN usuario.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN usuario.actived IS 'TRUE = activado | FALSE = desactivado';


--
-- TOC entry 204 (class 1259 OID 32920)
-- Name: usuario_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "usuario_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "usuario_Id_seq" OWNER TO postgres;

--
-- TOC entry 2301 (class 0 OID 0)
-- Dependencies: 204
-- Name: SEQUENCE "usuario_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "usuario_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 174 (class 1259 OID 32777)
-- Name: usuario_credencial_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE usuario_credencial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE usuario_credencial_id_seq OWNER TO postgres;

--
-- TOC entry 2302 (class 0 OID 0)
-- Dependencies: 174
-- Name: SEQUENCE usuario_credencial_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE usuario_credencial_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 179 (class 1259 OID 32821)
-- Name: usuario_credencial; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE usuario_credencial (
    id bigint DEFAULT nextval('usuario_credencial_id_seq'::regclass) NOT NULL,
    usuario_id bigint NOT NULL,
    credencial_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE usuario_credencial OWNER TO postgres;

--
-- TOC entry 205 (class 1259 OID 32922)
-- Name: usuario_credencial_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "usuario_credencial_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "usuario_credencial_Id_seq" OWNER TO postgres;

--
-- TOC entry 2303 (class 0 OID 0)
-- Dependencies: 205
-- Name: SEQUENCE "usuario_credencial_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "usuario_credencial_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 2214 (class 0 OID 32779)
-- Dependencies: 175
-- Data for Name: bitacora; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) FROM stdin;
1	1	identificación	NINGUNA	\N	\N	2015-02-06 13:59:54
2	1	identificación	NINGUNA	\N	\N	2015-02-24 15:14:49
\.


--
-- TOC entry 2304 (class 0 OID 0)
-- Dependencies: 180
-- Name: bitacora_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"bitacora_Id_seq"', 1, false);


--
-- TOC entry 2305 (class 0 OID 0)
-- Dependencies: 170
-- Name: bitacora_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('bitacora_id_seq', 2, true);


--
-- TOC entry 2306 (class 0 OID 0)
-- Dependencies: 181
-- Name: ciudad_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"ciudad_Id_seq"', 1, false);


--
-- TOC entry 2245 (class 0 OID 32925)
-- Dependencies: 206
-- Data for Name: control_calidad; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY control_calidad ("Id", fecha, turno, brix, ph, ar, sacarosa, pureza, id_empleado, id_proveedor, "empleado_Id", "proveedor_Id") FROM stdin;
\.


--
-- TOC entry 2307 (class 0 OID 0)
-- Dependencies: 182
-- Name: control_calidad_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"control_calidad_Id_seq"', 1, false);


--
-- TOC entry 2215 (class 0 OID 32791)
-- Dependencies: 176
-- Data for Name: credencial; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY credencial (id, nombre, created_at, updated_at, deleted_at) FROM stdin;
1	admin	2015-02-05 21:56:24.133	2015-02-05 21:56:24.133	\N
2	usuario	2015-02-05 21:56:24.133	2015-02-05 21:56:24.133	\N
\.


--
-- TOC entry 2308 (class 0 OID 0)
-- Dependencies: 183
-- Name: credencial_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"credencial_Id_seq"', 1, false);


--
-- TOC entry 2309 (class 0 OID 0)
-- Dependencies: 171
-- Name: credencial_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('credencial_id_seq', 2, true);


--
-- TOC entry 2310 (class 0 OID 0)
-- Dependencies: 184
-- Name: dato_usuario_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"dato_usuario_Id_seq"', 1, false);


--
-- TOC entry 2246 (class 0 OID 32931)
-- Dependencies: 207
-- Data for Name: detalle_empaque; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY detalle_empaque ("Id", cantidad, id_insumo, id_empaque, "insumo_Id", "empaque_Id") FROM stdin;
\.


--
-- TOC entry 2311 (class 0 OID 0)
-- Dependencies: 185
-- Name: detalle_empaque_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"detalle_empaque_Id_seq"', 1, false);


--
-- TOC entry 2247 (class 0 OID 32937)
-- Dependencies: 208
-- Data for Name: detalle_entrada; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY detalle_entrada ("Id", cantidad, valor, fecha_fabricacion, fecha_vencimiento, id_doc, id_insumo, "entrada_bodega_Id", "insumo_Id") FROM stdin;
\.


--
-- TOC entry 2312 (class 0 OID 0)
-- Dependencies: 186
-- Name: detalle_entrada_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"detalle_entrada_Id_seq"', 1, false);


--
-- TOC entry 2248 (class 0 OID 32943)
-- Dependencies: 209
-- Data for Name: detalle_ingreso; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY detalle_ingreso ("Id", cantidad, "procedencia_caña", "peso_caña", num_vagon, id_ingreso, id_insumo, "ingreso_caña_Id", "insumo_Id") FROM stdin;
\.


--
-- TOC entry 2313 (class 0 OID 0)
-- Dependencies: 187
-- Name: detalle_ingreso_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"detalle_ingreso_Id_seq"', 1, false);


--
-- TOC entry 2249 (class 0 OID 32949)
-- Dependencies: 210
-- Data for Name: detalle_pago_trabajadores; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY detalle_pago_trabajadores ("Id", valor, id_pago_trabajadores, id_empleado, id_tipo_pago, "pago_trabajores_Id", "empleado_Id", "tipo_pago_Id") FROM stdin;
\.


--
-- TOC entry 2314 (class 0 OID 0)
-- Dependencies: 188
-- Name: detalle_pago_trabajadores_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"detalle_pago_trabajadores_Id_seq"', 1, false);


--
-- TOC entry 2250 (class 0 OID 32955)
-- Dependencies: 211
-- Data for Name: detalle_solicitud; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY detalle_solicitud ("Id", cantidad, fecha_fabricacion, fecha_vencimiento, id_solicitud, id_insumo, "insumo_Id", "solicitud_insumos_Id") FROM stdin;
\.


--
-- TOC entry 2315 (class 0 OID 0)
-- Dependencies: 189
-- Name: detalle_solicitud_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"detalle_solicitud_Id_seq"', 1, false);


--
-- TOC entry 2251 (class 0 OID 32961)
-- Dependencies: 212
-- Data for Name: empaque; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY empaque ("Id", id_empleado, fecha, "empleado_Id") FROM stdin;
\.


--
-- TOC entry 2316 (class 0 OID 0)
-- Dependencies: 190
-- Name: empaque_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"empaque_Id_seq"', 1, false);


--
-- TOC entry 2252 (class 0 OID 32967)
-- Dependencies: 213
-- Data for Name: empleado; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY empleado ("Id", nom_empleado, apell_empleado, telefono, direccion, id_tipo_id, "tipo_id_Id") FROM stdin;
\.


--
-- TOC entry 2317 (class 0 OID 0)
-- Dependencies: 191
-- Name: empleado_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"empleado_Id_seq"', 1, false);


--
-- TOC entry 2253 (class 0 OID 32973)
-- Dependencies: 214
-- Data for Name: empresa; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY empresa ("Id", nit, nom_empresa, razon_social, direccion, telefono, usuario_id) FROM stdin;
\.


--
-- TOC entry 2318 (class 0 OID 0)
-- Dependencies: 192
-- Name: empresa_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"empresa_Id_seq"', 1, false);


--
-- TOC entry 2254 (class 0 OID 32979)
-- Dependencies: 215
-- Data for Name: entrada_bodega; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY entrada_bodega ("Id", fecha, id_proveedor, "proveedor_Id") FROM stdin;
\.


--
-- TOC entry 2319 (class 0 OID 0)
-- Dependencies: 193
-- Name: entrada_bodega_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"entrada_bodega_Id_seq"', 1, false);


--
-- TOC entry 2255 (class 0 OID 32985)
-- Dependencies: 216
-- Data for Name: ingreso_caña; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY "ingreso_caña" ("Id", fecha, id_proveedor, id_empleado, "empleado_Id", "proveedor_Id") FROM stdin;
\.


--
-- TOC entry 2320 (class 0 OID 0)
-- Dependencies: 194
-- Name: ingreso_caña_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"ingreso_caña_Id_seq"', 1, false);


--
-- TOC entry 2256 (class 0 OID 32991)
-- Dependencies: 217
-- Data for Name: insumo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY insumo ("Id", desc_insumo, precio, id_tipo_insumo, "tipo_insumo_Id") FROM stdin;
\.


--
-- TOC entry 2321 (class 0 OID 0)
-- Dependencies: 195
-- Name: insumo_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"insumo_Id_seq"', 1, false);


--
-- TOC entry 2257 (class 0 OID 32997)
-- Dependencies: 218
-- Data for Name: inventario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY inventario ("Id", cantidad, saldo, id_tipo_doc, id_insumo, "tipo_doc_Id", "insumo_Id") FROM stdin;
\.


--
-- TOC entry 2322 (class 0 OID 0)
-- Dependencies: 196
-- Name: inventario_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"inventario_Id_seq"', 1, false);


--
-- TOC entry 2258 (class 0 OID 33003)
-- Dependencies: 219
-- Data for Name: pago_trabajores; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY pago_trabajores ("Id", fecha, periodo_inicio, periodo_fin, id_empresa, "empresa_Id") FROM stdin;
\.


--
-- TOC entry 2323 (class 0 OID 0)
-- Dependencies: 197
-- Name: pago_trabajores_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"pago_trabajores_Id_seq"', 1, false);


--
-- TOC entry 2259 (class 0 OID 33009)
-- Dependencies: 220
-- Data for Name: proveedor; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY proveedor ("Id", razon_social, direccion, telefono, id_ciudad, "ciudad_Id") FROM stdin;
\.


--
-- TOC entry 2324 (class 0 OID 0)
-- Dependencies: 198
-- Name: proveedor_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"proveedor_Id_seq"', 1, false);


--
-- TOC entry 2216 (class 0 OID 32799)
-- Dependencies: 177
-- Data for Name: recordar_me; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY recordar_me (id, usuario_id, ip_address, hash_cookie, created_at) FROM stdin;
\.


--
-- TOC entry 2325 (class 0 OID 0)
-- Dependencies: 172
-- Name: recordar_me_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('recordar_me_id_seq', 1, false);


--
-- TOC entry 2260 (class 0 OID 33015)
-- Dependencies: 221
-- Data for Name: solicitud_insumos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY solicitud_insumos ("Id", fecha, id_proveedor, id_empleado, "proveedor_Id", "empleado_Id") FROM stdin;
\.


--
-- TOC entry 2326 (class 0 OID 0)
-- Dependencies: 199
-- Name: solicitud_insumos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"solicitud_insumos_Id_seq"', 1, false);


--
-- TOC entry 2261 (class 0 OID 33021)
-- Dependencies: 222
-- Data for Name: tipo_doc; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY tipo_doc ("Id", desc_tipo_doc) FROM stdin;
\.


--
-- TOC entry 2327 (class 0 OID 0)
-- Dependencies: 200
-- Name: tipo_doc_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"tipo_doc_Id_seq"', 1, false);


--
-- TOC entry 2262 (class 0 OID 33027)
-- Dependencies: 223
-- Data for Name: tipo_id; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY tipo_id ("Id", desc_tipo_id) FROM stdin;
\.


--
-- TOC entry 2328 (class 0 OID 0)
-- Dependencies: 201
-- Name: tipo_id_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"tipo_id_Id_seq"', 1, false);


--
-- TOC entry 2263 (class 0 OID 33033)
-- Dependencies: 224
-- Data for Name: tipo_insumo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY tipo_insumo ("Id", desc_tipo_insumo) FROM stdin;
\.


--
-- TOC entry 2329 (class 0 OID 0)
-- Dependencies: 202
-- Name: tipo_insumo_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"tipo_insumo_Id_seq"', 1, false);


--
-- TOC entry 2264 (class 0 OID 33039)
-- Dependencies: 225
-- Data for Name: tipo_pago; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY tipo_pago ("Id", desc_tipo_pago) FROM stdin;
\.


--
-- TOC entry 2330 (class 0 OID 0)
-- Dependencies: 203
-- Name: tipo_pago_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"tipo_pago_Id_seq"', 1, false);


--
-- TOC entry 2217 (class 0 OID 32808)
-- Dependencies: 178
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) FROM stdin;
2	consultor	202cb962ac59075b964b07152d234b70	t	\N	2015-02-06 08:13:39.58	2015-02-06 08:13:39.58	2015-02-06 14:15:20
1	admin	202cb962ac59075b964b07152d234b70	t	2015-02-24 15:14:49	2015-02-05 21:56:24.133	2015-02-05 21:56:24.133	\N
4	adminisrador	202cb962ac59075b964b07152d234b70	t	\N	2015-02-24 09:15:26.533	2015-02-24 09:15:26.533	\N
\.


--
-- TOC entry 2331 (class 0 OID 0)
-- Dependencies: 204
-- Name: usuario_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"usuario_Id_seq"', 1, false);


--
-- TOC entry 2218 (class 0 OID 32821)
-- Dependencies: 179
-- Data for Name: usuario_credencial; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY usuario_credencial (id, usuario_id, credencial_id, created_at) FROM stdin;
1	1	1	2015-02-05 21:56:24.133
\.


--
-- TOC entry 2332 (class 0 OID 0)
-- Dependencies: 205
-- Name: usuario_credencial_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"usuario_credencial_Id_seq"', 1, false);


--
-- TOC entry 2333 (class 0 OID 0)
-- Dependencies: 174
-- Name: usuario_credencial_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('usuario_credencial_id_seq', 1, true);


--
-- TOC entry 2334 (class 0 OID 0)
-- Dependencies: 173
-- Name: usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('usuario_id_seq', 4, true);


--
-- TOC entry 2016 (class 2606 OID 32788)
-- Name: pkbitacora; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY bitacora
    ADD CONSTRAINT pkbitacora PRIMARY KEY (id);


--
-- TOC entry 2035 (class 2606 OID 32930)
-- Name: pkcontrol_calidad; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY control_calidad
    ADD CONSTRAINT pkcontrol_calidad PRIMARY KEY ("Id");


--
-- TOC entry 2018 (class 2606 OID 32798)
-- Name: pkcredencial; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY credencial
    ADD CONSTRAINT pkcredencial PRIMARY KEY (id);


--
-- TOC entry 2037 (class 2606 OID 32936)
-- Name: pkdetalle_empaque; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY detalle_empaque
    ADD CONSTRAINT pkdetalle_empaque PRIMARY KEY ("Id");


--
-- TOC entry 2039 (class 2606 OID 32942)
-- Name: pkdetalle_entrada; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY detalle_entrada
    ADD CONSTRAINT pkdetalle_entrada PRIMARY KEY ("Id");


--
-- TOC entry 2041 (class 2606 OID 32948)
-- Name: pkdetalle_ingreso; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY detalle_ingreso
    ADD CONSTRAINT pkdetalle_ingreso PRIMARY KEY ("Id");


--
-- TOC entry 2043 (class 2606 OID 32954)
-- Name: pkdetalle_pago_trabajadores; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY detalle_pago_trabajadores
    ADD CONSTRAINT pkdetalle_pago_trabajadores PRIMARY KEY ("Id");


--
-- TOC entry 2045 (class 2606 OID 32960)
-- Name: pkdetalle_solicitud; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY detalle_solicitud
    ADD CONSTRAINT pkdetalle_solicitud PRIMARY KEY ("Id");


--
-- TOC entry 2047 (class 2606 OID 32966)
-- Name: pkempaque; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY empaque
    ADD CONSTRAINT pkempaque PRIMARY KEY ("Id");


--
-- TOC entry 2049 (class 2606 OID 32972)
-- Name: pkempleado; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY empleado
    ADD CONSTRAINT pkempleado PRIMARY KEY ("Id");


--
-- TOC entry 2051 (class 2606 OID 32978)
-- Name: pkempresa; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY empresa
    ADD CONSTRAINT pkempresa PRIMARY KEY ("Id");


--
-- TOC entry 2053 (class 2606 OID 32984)
-- Name: pkentrada_bodega; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY entrada_bodega
    ADD CONSTRAINT pkentrada_bodega PRIMARY KEY ("Id");


--
-- TOC entry 2055 (class 2606 OID 32990)
-- Name: pkingreso_caña; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY "ingreso_caña"
    ADD CONSTRAINT "pkingreso_caña" PRIMARY KEY ("Id");


--
-- TOC entry 2057 (class 2606 OID 32996)
-- Name: pkinsumo; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY insumo
    ADD CONSTRAINT pkinsumo PRIMARY KEY ("Id");


--
-- TOC entry 2059 (class 2606 OID 33002)
-- Name: pkinventario; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY inventario
    ADD CONSTRAINT pkinventario PRIMARY KEY ("Id");


--
-- TOC entry 2061 (class 2606 OID 33008)
-- Name: pkpago_trabajores; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY pago_trabajores
    ADD CONSTRAINT pkpago_trabajores PRIMARY KEY ("Id");


--
-- TOC entry 2063 (class 2606 OID 33014)
-- Name: pkproveedor; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY proveedor
    ADD CONSTRAINT pkproveedor PRIMARY KEY ("Id");


--
-- TOC entry 2020 (class 2606 OID 32805)
-- Name: pkrecordar_me; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY recordar_me
    ADD CONSTRAINT pkrecordar_me PRIMARY KEY (id);


--
-- TOC entry 2065 (class 2606 OID 33020)
-- Name: pksolicitud_insumos; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY solicitud_insumos
    ADD CONSTRAINT pksolicitud_insumos PRIMARY KEY ("Id");


--
-- TOC entry 2067 (class 2606 OID 33026)
-- Name: pktipo_doc; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY tipo_doc
    ADD CONSTRAINT pktipo_doc PRIMARY KEY ("Id");


--
-- TOC entry 2069 (class 2606 OID 33032)
-- Name: pktipo_id; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY tipo_id
    ADD CONSTRAINT pktipo_id PRIMARY KEY ("Id");


--
-- TOC entry 2071 (class 2606 OID 33038)
-- Name: pktipo_insumo; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY tipo_insumo
    ADD CONSTRAINT pktipo_insumo PRIMARY KEY ("Id");


--
-- TOC entry 2073 (class 2606 OID 33044)
-- Name: pktipo_pago; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY tipo_pago
    ADD CONSTRAINT pktipo_pago PRIMARY KEY ("Id");


--
-- TOC entry 2024 (class 2606 OID 32816)
-- Name: pkusuario; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY usuario
    ADD CONSTRAINT pkusuario PRIMARY KEY (id);


--
-- TOC entry 2030 (class 2606 OID 32827)
-- Name: pkusuario_credencial; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT pkusuario_credencial PRIMARY KEY (id);


--
-- TOC entry 2013 (class 1259 OID 32789)
-- Name: bitacora_fecha_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "bitacora_fecha_Idx" ON bitacora USING btree (fecha);


--
-- TOC entry 2014 (class 1259 OID 32790)
-- Name: bitacora_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "bitacora_usuario_id_Idx" ON bitacora USING btree (usuario_id);


--
-- TOC entry 2021 (class 1259 OID 32806)
-- Name: recordar_me_ip_address_hash_cookie_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "recordar_me_ip_address_hash_cookie_Idx" ON recordar_me USING btree (ip_address, hash_cookie);


--
-- TOC entry 2022 (class 1259 OID 32807)
-- Name: recordar_me_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "recordar_me_usuario_id_Idx" ON recordar_me USING btree (usuario_id);


--
-- TOC entry 2025 (class 1259 OID 32817)
-- Name: usuario_actived_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_actived_Idx" ON usuario USING btree (actived);


--
-- TOC entry 2031 (class 1259 OID 32828)
-- Name: usuario_credencial_credencial_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_credencial_credencial_id_Idx" ON usuario_credencial USING btree (credencial_id);


--
-- TOC entry 2032 (class 1259 OID 32829)
-- Name: usuario_credencial_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_credencial_usuario_id_Idx" ON usuario_credencial USING btree (usuario_id);


--
-- TOC entry 2033 (class 1259 OID 32830)
-- Name: usuario_credencial_usuario_id_credencial_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "usuario_credencial_usuario_id_credencial_id_Idx" ON usuario_credencial USING btree (usuario_id, credencial_id);


--
-- TOC entry 2026 (class 1259 OID 32818)
-- Name: usuario_deleted_at_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_deleted_at_Idx" ON usuario USING btree (deleted_at);


--
-- TOC entry 2027 (class 1259 OID 32819)
-- Name: usuario_user_name_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "usuario_user_name_Idx" ON usuario USING btree (user_name);


--
-- TOC entry 2028 (class 1259 OID 32820)
-- Name: usuario_user_name_password_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_user_name_password_Idx" ON usuario USING btree (user_name, password);


--
-- TOC entry 2074 (class 2606 OID 32831)
-- Name: fk_bitacora_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY bitacora
    ADD CONSTRAINT fk_bitacora_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2078 (class 2606 OID 33045)
-- Name: fk_control_calidad_empleado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY control_calidad
    ADD CONSTRAINT fk_control_calidad_empleado FOREIGN KEY ("empleado_Id") REFERENCES empleado("Id");


--
-- TOC entry 2079 (class 2606 OID 33050)
-- Name: fk_control_calidad_proveedor; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY control_calidad
    ADD CONSTRAINT fk_control_calidad_proveedor FOREIGN KEY ("proveedor_Id") REFERENCES proveedor("Id");


--
-- TOC entry 2080 (class 2606 OID 33055)
-- Name: fk_detalle_empaque_empaque; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_empaque
    ADD CONSTRAINT fk_detalle_empaque_empaque FOREIGN KEY ("empaque_Id") REFERENCES empaque("Id");


--
-- TOC entry 2081 (class 2606 OID 33060)
-- Name: fk_detalle_empaque_insumo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_empaque
    ADD CONSTRAINT fk_detalle_empaque_insumo FOREIGN KEY ("insumo_Id") REFERENCES insumo("Id");


--
-- TOC entry 2082 (class 2606 OID 33065)
-- Name: fk_detalle_entrada_entrada_bodega; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_entrada
    ADD CONSTRAINT fk_detalle_entrada_entrada_bodega FOREIGN KEY ("entrada_bodega_Id") REFERENCES entrada_bodega("Id");


--
-- TOC entry 2083 (class 2606 OID 33070)
-- Name: fk_detalle_entrada_insumo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_entrada
    ADD CONSTRAINT fk_detalle_entrada_insumo FOREIGN KEY ("insumo_Id") REFERENCES insumo("Id");


--
-- TOC entry 2084 (class 2606 OID 33075)
-- Name: fk_detalle_ingreso_ingreso_caña; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_ingreso
    ADD CONSTRAINT "fk_detalle_ingreso_ingreso_caña" FOREIGN KEY ("ingreso_caña_Id") REFERENCES "ingreso_caña"("Id");


--
-- TOC entry 2085 (class 2606 OID 33080)
-- Name: fk_detalle_ingreso_insumo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_ingreso
    ADD CONSTRAINT fk_detalle_ingreso_insumo FOREIGN KEY ("insumo_Id") REFERENCES insumo("Id");


--
-- TOC entry 2086 (class 2606 OID 33085)
-- Name: fk_detalle_pago_trabajadores_empleado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_pago_trabajadores
    ADD CONSTRAINT fk_detalle_pago_trabajadores_empleado FOREIGN KEY ("empleado_Id") REFERENCES empleado("Id");


--
-- TOC entry 2087 (class 2606 OID 33090)
-- Name: fk_detalle_pago_trabajadores_pago_trabajores; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_pago_trabajadores
    ADD CONSTRAINT fk_detalle_pago_trabajadores_pago_trabajores FOREIGN KEY ("pago_trabajores_Id") REFERENCES pago_trabajores("Id");


--
-- TOC entry 2088 (class 2606 OID 33095)
-- Name: fk_detalle_pago_trabajadores_tipo_pago; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_pago_trabajadores
    ADD CONSTRAINT fk_detalle_pago_trabajadores_tipo_pago FOREIGN KEY ("tipo_pago_Id") REFERENCES tipo_pago("Id");


--
-- TOC entry 2089 (class 2606 OID 33100)
-- Name: fk_detalle_solicitud_insumo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_solicitud
    ADD CONSTRAINT fk_detalle_solicitud_insumo FOREIGN KEY ("insumo_Id") REFERENCES insumo("Id");


--
-- TOC entry 2090 (class 2606 OID 33105)
-- Name: fk_detalle_solicitud_solicitud_insumos; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_solicitud
    ADD CONSTRAINT fk_detalle_solicitud_solicitud_insumos FOREIGN KEY ("solicitud_insumos_Id") REFERENCES solicitud_insumos("Id");


--
-- TOC entry 2091 (class 2606 OID 33110)
-- Name: fk_empaque_empleado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY empaque
    ADD CONSTRAINT fk_empaque_empleado FOREIGN KEY ("empleado_Id") REFERENCES empleado("Id");


--
-- TOC entry 2092 (class 2606 OID 33115)
-- Name: fk_empleado_tipo_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY empleado
    ADD CONSTRAINT fk_empleado_tipo_id FOREIGN KEY ("tipo_id_Id") REFERENCES tipo_id("Id");


--
-- TOC entry 2093 (class 2606 OID 33120)
-- Name: fk_entrada_bodega_proveedor; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY entrada_bodega
    ADD CONSTRAINT fk_entrada_bodega_proveedor FOREIGN KEY ("proveedor_Id") REFERENCES proveedor("Id");


--
-- TOC entry 2094 (class 2606 OID 33125)
-- Name: fk_ingreso_caña_empleado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "ingreso_caña"
    ADD CONSTRAINT "fk_ingreso_caña_empleado" FOREIGN KEY ("empleado_Id") REFERENCES empleado("Id");


--
-- TOC entry 2095 (class 2606 OID 33130)
-- Name: fk_ingreso_caña_proveedor; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "ingreso_caña"
    ADD CONSTRAINT "fk_ingreso_caña_proveedor" FOREIGN KEY ("proveedor_Id") REFERENCES proveedor("Id");


--
-- TOC entry 2096 (class 2606 OID 33135)
-- Name: fk_insumo_tipo_insumo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY insumo
    ADD CONSTRAINT fk_insumo_tipo_insumo FOREIGN KEY ("tipo_insumo_Id") REFERENCES tipo_insumo("Id");


--
-- TOC entry 2097 (class 2606 OID 33140)
-- Name: fk_inventario_insumo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY inventario
    ADD CONSTRAINT fk_inventario_insumo FOREIGN KEY ("insumo_Id") REFERENCES insumo("Id");


--
-- TOC entry 2098 (class 2606 OID 33145)
-- Name: fk_inventario_tipo_doc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY inventario
    ADD CONSTRAINT fk_inventario_tipo_doc FOREIGN KEY ("tipo_doc_Id") REFERENCES tipo_doc("Id");


--
-- TOC entry 2099 (class 2606 OID 33150)
-- Name: fk_pago_trabajores_empresa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY pago_trabajores
    ADD CONSTRAINT fk_pago_trabajores_empresa FOREIGN KEY ("empresa_Id") REFERENCES empresa("Id");


--
-- TOC entry 2075 (class 2606 OID 32836)
-- Name: fk_recordar_me_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY recordar_me
    ADD CONSTRAINT fk_recordar_me_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2100 (class 2606 OID 33155)
-- Name: fk_solicitud_insumos_empleado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY solicitud_insumos
    ADD CONSTRAINT fk_solicitud_insumos_empleado FOREIGN KEY ("empleado_Id") REFERENCES empleado("Id");


--
-- TOC entry 2101 (class 2606 OID 33160)
-- Name: fk_solicitud_insumos_proveedor; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY solicitud_insumos
    ADD CONSTRAINT fk_solicitud_insumos_proveedor FOREIGN KEY ("proveedor_Id") REFERENCES proveedor("Id");


--
-- TOC entry 2076 (class 2606 OID 32841)
-- Name: fk_usuario_credencial_credencial; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT fk_usuario_credencial_credencial FOREIGN KEY (credencial_id) REFERENCES credencial(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2077 (class 2606 OID 32846)
-- Name: fk_usuario_credencial_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT fk_usuario_credencial_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2270 (class 0 OID 0)
-- Dependencies: 5
-- Name: public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM postgres;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO PUBLIC;


-- Completed on 2015-02-26 14:30:43

--
-- PostgreSQL database dump complete
--

